[package]
edition.workspace = true
name = "haze"
version = "0.0.0"

[dependencies]
diagnostics = {path = "../diagnostics"}
lexer = {path = "../lexer"}
project = {path = "../project"}
thread = {path = "../thread"}
