[package]
edition.workspace = true
name = "lexer"
version = "0.0.0"

[dependencies]
logos = "0.13.0"
syntax = {path = "../syntax"}
text-size = "1.1.1"
token = {path = "../token"}

[dev-dependencies]
expect-test = "1.4.1"
